{
 "title": "Execution Dashborad Phase 2",
 "time": { "from": "2021-12-11T06:37:53.000Z", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "startDate", "label": "Start Date", "query": "2024-11-13 11:00:00" },
   { "name": "endDate", "label": "End Date", "query": "2024-11-15" },
   {
    "name": "env",
    "label": "Environment",
    "query": "SELECT  Distinct \"Environment\" FROM  \"Account_Reports\".\"RunSets\""
   },
   {
    "name": "TestType",
    "label": "Test Type",
    "query": "SELECT DISTINCT  \"TestType\" FROM \"Account_Reports\".\"RunSets\" WHERE \"TestType\" IS NOT NULL ORDER BY 1 ASC"
   },
   {
    "name": "product",
    "label": "Application",
    "query": "SELECT DISTINCT \"Product\" FROM \"Account_Reports\".\"RunSets\" WHERE \"Product\" IS NOT NULL\nORDER BY \"Product\" ASC"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Run Set’s Execution Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "Select\n  COUNT(*) AS value,\n  NOW() as time,\n  TFinal.\"RunStatus\" AS metric\nFROM\n(\n    SELECT\n      *\n    FROM\n      (\n        SELECT\n          BusinessFlows.\"RunStatus\",\n          Row_Number() Over(\n            Partition BY businessflows.\"EntityId\"            \n            Order By\n              businessflows.\"StartTimeStamp\" DESC\n          ) AS ExecIndex\n        FROM\n          \"Account_Reports\".\"RunSets\" runset\n          INNER JOIN \"Account_Reports\".\"Runners\" runner ON runner.\"AccountReportDbRunSetId\" = runset.\"Id\"\n          INNER JOIN \"Account_Reports\".\"BusinessFlows\" businessflows ON businessflows.\"AccountReportDbRunnerId\" = runner.\"Id\"\n        Where          \n          runset.\"Product\" in ($product) AND           \n          runset.\"TestType\" IS NOT NULL AND runset.\"TestType\" IN($TestType) AND          \n          CAST(BusinessFlows.\"StartTimeStamp\" AS timestamp) >= CAST('$startDate' as timestamp) AND \n          CAST(BusinessFlows.\"StartTimeStamp\" AS timestamp) <= CAST('$endDate' as timestamp) --CAST('2023-02-25' AS DATE)\n      ) TRawData\n    WHERE\n      ExecIndex = 1\n  ) TFinal\ngroup by\n  TFinal.\"RunStatus\"\norder by\n  TFinal.\"RunStatus\""
    }
   ]
  },
  {
   "title": "Total Cummulative Execution Time (in Minutes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  round((((sum(TIME1))/60000)::Decimal),5) as \"Total Cummulative Execution Time (in Minutes)\"\r\nFROM\r\n(\r\n    SELECT\r\n      *\r\n    FROM\r\n      (\r\n        SELECT\r\n          BusinessFlows.\"RunStatus\",\r\n          BUSINESSFLOWS.\"ElapsedEndTimeStamp\" AS TIME1,\r\n          Row_Number() Over(\r\n            Partition BY businessflows.\"EntityId\"            \r\n            Order By\r\n              businessflows.\"StartTimeStamp\" DESC\r\n          ) AS ExecIndex\r\n        FROM\r\n          \"Account_Reports\".\"RunSets\" runset\r\n          INNER JOIN \"Account_Reports\".\"Runners\" runner ON runner.\"AccountReportDbRunSetId\" = runset.\"Id\"\r\n          INNER JOIN \"Account_Reports\".\"BusinessFlows\" businessflows ON businessflows.\"AccountReportDbRunnerId\" = runner.\"Id\"\r\n        Where          \r\n          runset.\"Product\" in ($product) AND           \r\n          runset.\"TestType\" IS NOT NULL AND runset.\"TestType\" IN($TestType) AND          \r\n          CAST(BusinessFlows.\"StartTimeStamp\" AS timestamp) >= CAST('$startDate' as timestamp) AND \r\n          CAST(BusinessFlows.\"StartTimeStamp\" AS timestamp) <= CAST('$endDate' as timestamp) --CAST('2023-02-25' AS DATE)\r\n      ) TRawData\r\n    WHERE\r\n      ExecIndex = 1\r\n  ) TFinal\r\ngroup by\r\n  TFinal.\"RunStatus\"\r\norder by\r\n  TFinal.\"RunStatus\""
    }
   ]
  },
  {
   "title": "Total Execution Time (in Minutes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select\r\n  round((((sum(TIME1))/(60000*4))::Decimal),5) as \"Total Execution Time (in Minutes)\"\r\nFROM\r\n(\r\n    SELECT\r\n      *\r\n    FROM\r\n      (\r\n        SELECT\r\n          BusinessFlows.\"RunStatus\",\r\n          BUSINESSFLOWS.\"ElapsedEndTimeStamp\" AS TIME1,\r\n          Row_Number() Over(\r\n            Partition BY businessflows.\"EntityId\"            \r\n            Order By\r\n              businessflows.\"StartTimeStamp\" DESC\r\n          ) AS ExecIndex\r\n        FROM\r\n          \"Account_Reports\".\"RunSets\" runset\r\n          INNER JOIN \"Account_Reports\".\"Runners\" runner ON runner.\"AccountReportDbRunSetId\" = runset.\"Id\"\r\n          INNER JOIN \"Account_Reports\".\"BusinessFlows\" businessflows ON businessflows.\"AccountReportDbRunnerId\" = runner.\"Id\"\r\n        Where          \r\n          runset.\"Product\" in ($product) AND           \r\n          runset.\"TestType\" IS NOT NULL AND runset.\"TestType\" IN($TestType) AND          \r\n          CAST(BusinessFlows.\"StartTimeStamp\" AS timestamp) >= CAST('$startDate' as timestamp) AND \r\n          CAST(BusinessFlows.\"StartTimeStamp\" AS timestamp) <= CAST('$endDate' as timestamp) --CAST('2023-02-25' AS DATE)\r\n      ) TRawData\r\n    WHERE\r\n      ExecIndex = 1\r\n  ) TFinal\r\ngroup by\r\n  TFinal.\"RunStatus\"\r\norder by\r\n  TFinal.\"RunStatus\""
    }
   ]
  },
  {
   "title": "Business Flow Level Report",
   "type": "table",
   "description": "Please Use Column Filter to Reduce Data.",
   "gridPos": { "h": 49, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "Select\n  TBFs.RSName \"Runset Name\",\n  TBFs.BFName \"Business Flow Name\",\n  TBFs.\"InstanceGUID\" \"Business Flow InstanceGUID\",\n  TBFs.\"ExecutionId\" \"Business Flow Report Hyperlink\",\n  TBFs.BFStartTime \"Start Time\",\n  TBFs.BFEndTime \"End Time\",\n  TBFs.BFExecDuration \"Execution Duration(Seconds)\",\n  TBFs.BFStatus \"Business Flow Status\",\n  FA.ActivityName \"Failed Activity Name\",\n  FA.ActionName \"Failed Action Name\",\n  FA.ErrorInfo \"Error Info\",\n  TBFs.RSetStartTime\nFROM\n  (\n    Select\n      *\n    from\n      (\n         Select\n          runset.\"Id\" RsId,\n          runset.\"Name\" RSName,\n          businessflows.\"Id\" BFId,\n          businessflows.\"Name\" BFName,\n          businessflows.\"InstanceGUID\",\n          businessflows.\"ExecutionId\",\n          businessflows.\"StartTimeStamp\" BFStartTime,          \n          CASE businessflows.\"EndTimeStamp\" WHEN '-infinity' THEN null ELSE businessflows.\"EndTimeStamp\" END BFEndTime,          \n          CASE businessflows.\"EndTimeStamp\"  WHEN  '-infinity' THEN\n\t\t  \t\tCASE LOWER(businessflows.\"RunStatus\") WHEN  'canceled' THEN 0\n\t\t  \t\t\tELSE EXTRACT(EPOCH from (NOW() - businessflows.\"StartTimeStamp\") ) END \n\t\tELSE businessflows.\"ElapsedEndTimeStamp\" /1000 END BFExecDuration,        \n          businessflows.\"RunStatus\" BFStatus,\n          Row_Number() Over(\n            Partition BY businessflows.\"EntityId\"\n            Order By\n              businessflows.\"StartTimeStamp\" DESC\n          ) AS ExecIndex,\n          runset.\"StartTimeStamp\" RSetStartTime\n        from\n          \"Account_Reports\".\"RunSets\" runset\n          INNER JOIN \"Account_Reports\".\"Runners\" runner ON runner.\"AccountReportDbRunSetId\" = runset.\"Id\"\n          INNER JOIN \"Account_Reports\".\"BusinessFlows\" businessflows ON businessflows.\"AccountReportDbRunnerId\" = runner.\"Id\"\n        Where\n          runset.\"Environment\" in ($env) AND\n          runset.\"Product\" IS NOT NULL AND \n          runset.\"Product\" in ($product) AND          \n          runset.\"TestType\" IS NOT NULL AND\n          runset.\"TestType\" IN($TestType) AND\n          CAST(runset.\"StartTimeStamp\" AS timestamp) >= CAST('$startDate' as timestamp) AND\n          CAST(runset.\"StartTimeStamp\" AS timestamp) <= CAST('$endDate' as timestamp)           \n      ) T\n    Where\n      ExecIndex = 1\n  ) TBFs\n  LEFT JOIN (\n    Select\n      *\n    from\n      (\n        Select\n          runset.\"Id\" RsetId,\n          businessflows.\"Id\" BFId,\n          businessflows.\"ExecutionId\" BFExecId,\n\t\t  businessflows.\"InstanceGUID\" BFInstanceGUID,\n          activities.\"Name\" ActivityName,\n          activities.\"RunStatus\" ActivityStatus,\n          ROW_NUMBER() Over(\n            Partition By businessflows.\"EntityId\"\t\t\t  \n            Order by\n              activities.\"StartTimeStamp\" DESC\n          ) ExecIndex,\n          actions.\"Name\" ActionName,\n          actions.\"RunStatus\" ActionStatus,\n          actions.\"Error\" ErrorInfo,\n          actions.\"StartTimeStamp\"\t\t\t  \n        FROM\n          \"Account_Reports\".\"RunSets\" runset\n          INNER JOIN \"Account_Reports\".\"Runners\" runner ON runner.\"AccountReportDbRunSetId\" = runset.\"Id\"\n          INNER JOIN \"Account_Reports\".\"BusinessFlows\" businessflows ON businessflows.\"AccountReportDbRunnerId\" = runner.\"Id\"\n          INNER JOIN \"Account_Reports\".\"ActivityGroups\" activitygroups ON activitygroups.\"AccountReportDbBusinessFlowId\" = businessflows.\"Id\"\n          INNER JOIN \"Account_Reports\".\"Activities\" activities ON activities.\"AccountReportDbActivityGroupId\" = activitygroups.\"Id\"\n          INNER JOIN \"Account_Reports\".\"Actions\" actions ON actions.\"AccountReportDbActivityId\" = activities.\"Id\"\n        Where\n        \n          activities.\"RunStatus\" = 'Failed' AND\n\t\t      actions.\"RunStatus\" = 'Failed' AND\n          runset.\"Environment\" in ($env) AND\n          runset.\"Product\" IS NOT NULL AND \n          runset.\"Product\" in ($product) AND          \n          runset.\"TestType\" IS NOT NULL AND\n          runset.\"TestType\" IN($TestType) AND\n          CAST(runset.\"StartTimeStamp\" AS timestamp) >= CAST('$startDate' as timestamp) AND\n          CAST(runset.\"StartTimeStamp\" AS timestamp) <= CAST('$endDate' as timestamp) \n      ) TAct\n    Where\n      ExecIndex = 1\n  ) FA ON FA.BFId = TBFs.BFId AND FA.BFInstanceGUID = TBFs.\"InstanceGUID\"\nORDER BY\n  TBFs.BFStartTime DESC"
    }
   ]
  }
 ]
}